-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 12, 2019 at 12:12 PM
-- Server version: 10.1.39-MariaDB
-- PHP Version: 7.3.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `search`
--

-- --------------------------------------------------------

--
-- Table structure for table `website`
--

CREATE TABLE `website` (
  `id` int(11) NOT NULL,
  `site_title` varchar(200) NOT NULL,
  `site_link` varchar(400) NOT NULL,
  `site_key` varchar(200) NOT NULL,
  `site_des` text NOT NULL,
  `site_img` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `website`
--

INSERT INTO `website` (`id`, `site_title`, `site_link`, `site_key`, `site_des`, `site_img`) VALUES
(1, 'Facebook - Log In or Sign Up', 'https://www.facebook.com/', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark', 'Create an account or log into Facebook. Connect with friends, family and other people you know. Share photos and videos, send messages and get updates.\r\nFacebook, Inc. is an American online social media and social networking service company based in Menlo Park, California. It was founded by Mark Zuckerberg, along with fellow Harvard College students and roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz and Chris Hughes.', 'facebook-2661207_960_720.jpg'),
(2, 'Log in to Facebook', 'https://www.facebook.com/', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark', 'Log in to Facebook to start sharing and connecting with your friends and family.', 'fbc.jpg'),
(3, 'Free Facebook', 'https://www.facebook.com/', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark', 'Create an account or log into Facebook. Connect with friends ...', 'facebook-logo.jpg'),
(4, 'Facebook Business', 'https://www.facebook.com/', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark', 'Facebook Business gives you the latest news, advertising tips ...', 'facebook_security_fb.jpg'),
(5, 'Facebook (@facebook) Â· Twitter', 'https://twitter.com/facebook', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark,twitter facebook', 'ICYMI ðŸ‘‡ðŸ’™ www.forbes.com/sites/maâ€¦\r\n4 days ago Â· Twitter', 'X4G0h2LY_400x400.png'),
(6, 'Usman Qureshi', 'https://www.facebook.com/usman.qureshi.73345', 'Usman,usman,qureshi,dinga,osman,C.E.O somani, takhar,ceo somani, ', '50% introvert\r\n50%extrovert...\r\nFGIAN\r\nPEACEAN\r\nUETIAN\r\nStudied at The Peace College Abbottabad\r\nStudies Chemical engineering at University of Engineering and Technology Peshawar Pakistan\r\nLives in Peshawar, Pakistan\r\nFrom Abbottabad', '48263157_1250726725059476_8967697830634323968_n.jpg'),
(7, 'Muhammad HaFeez', 'https://www.facebook.com/profile.php?id=100009872222625', 'hafeez,zeezu,muhammad hafeez,C.E.Omalik\'s co, takhar,moon,mr unknown', 'EmðŸ˜‹ Not A CigaretteðŸš­ that You Smoke And CrushðŸ˜‰\r\nEmðŸ˜Š A DrugðŸ¬ You Have To BegðŸ˜ For ðŸ˜ðŸ˜\r\nStudies Chemical engineering at UET Peshawar\r\nWent to Jinnah jam-e school and college haripur\r\nLives in Peshawar, Pakistan\r\nFrom Haripur, Pakistan\r\nSingle\r\nManages Proud Pakistani', 'zeezu.jpg'),
(8, 'Facebook - YouTube', 'https://www.youtube.com/channel/UCcr9tciZbuvJrEVAgIXCp8Q', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark,cambridge', 'The official channel of Facebook on YouTube. ... We\'re making some changes to Facebook that will help make it easier for you to find your community.', 'facebook.jpg'),
(9, 'Facebook, Inc. Social network company', 'https://www.facebook.com/', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark,cambridge,wikipedia facebook', 'Facebook, Inc. is an American online social media and social networking service company based in Menlo Park, California. It was founded by Mark Zuckerberg, along with fellow Harvard College students and roommates Eduardo Saverin, Andrew McCollum, Dustin Moskovitz and Chris Hughes. Wikipedia\r\nFounders: Mark Zuckerberg, Andrew McCollum, Dustin Moskovitz, Eduardo Saverin, Chris Hughes Trending\r\nFounded: February 2004, Cambridge, Massachusetts, United States\r\nStock price: FB (NASDAQ) US$188.36 -0.48 (-0.25%)\r\n26 Jun, 1:27 pm GMT-4 - Disclaimer\r\nCEO: Mark Zuckerberg\r\nHeadquarters: Menlo Park, California, United States\r\nCFO: David Wehner\r\nSubsidiaries: Facebook Germany Gmbh, LiveRail,', 'zuck.jpg'),
(10, 'Facebook Newsroom', 'https://newsroom.fb.com/', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark,cambridge,wikipedia facebook newsroom', 'By clicking or navigating the site, you agree to allow our collection of information on and off Facebook through cookies. Learn more, including about available ...', 'fb_opengraph.png'),
(11, 'Facebook - Apps on Google Play', 'https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en_US', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark,cambridge,wikipedia facebook, playstore app , fb app , ios app', ' Rating: 4.1 - â€Ž88,349,905 votes - â€ŽFree - â€ŽAndroid - â€ŽSocial Networking\r\nKeeping up with friends is faster and easier than ever. Share updates and photos, engage with friends and Pages, and stay connected to communities important ...', 'google.com embedded.jpeg'),
(12, 'Facebook - Wikipedia', 'https://en.wikipedia.org/wiki/Facebook', 'f,fa,fac,face,faceb,facebo,faceboo,facebook,fb,Facebook,Zuckerberg,Mark,cambridge,wikipedia facebook, wiki info fb', 'Facebook, Inc. is an American online social media and social networking service company based in Menlo Park, California. It was founded by Mark Zuckerberg, ...\r\nFoundedâ€Ž: â€ŽFebruary 4, 2004; 15 years ago in â€ŽC...	Total assetsâ€Ž: â€ŽUS$ 97.334 billion (2018)\r\nFounder(s)â€Ž: â€ŽMark Zuckerbergâ€Ž; â€ŽEduardo Saverinâ€Ž; ...	Employeesâ€Ž: â€Ž30,275 (June 30, 2018)\r\nPeople also ask', 'Facebook_02-w810h462.jpg'),
(13, 'WhatsApp', 'https://www.whatsapp.com/', 'whatsapp,whapp,whap,whats,whatsup,social networking, mobile ios android app, whatsapp , fb,', 'With WhatsApp, you\'ll get fast, simple, secure messaging and calling for free*, available on phones all over the world. * Data charges may apply. Contact your ...\r\nWhatsApp Messenger is a freeware, cross-platform messaging and Voice over IP service owned by Facebook. It allows users to send text messages and voice messages, make voice and video calls, and share images, documents, user locations, and other media.', 'google.com embedded (1).jpeg'),
(14, 'WhatsApp Web', 'https://www.whatsapp.com/', 'whatsapp,whapp,whap,whats,whatsup,social networking, mobile ios android app, whatsapp , fb, whatsapp web , computer pc , web, windows, desktop', 'Quickly send and receive WhatsApp messages right from ...\r\nDesktop Web', 'google.com embedded (2).jpeg'),
(15, 'Download', 'https://www.whatsapp.com/', 'whatsapp,whapp,whap,whats,whatsup,social networking, mobile ios android app, whatsapp , fb, whatsapp web , computer pc , mac  download for pcweb, windows, desktop', 'Mac or Windows PC. WhatsApp must be installed on your phone ...', 'google.com embedded (3).jpeg'),
(16, 'WhatsApp Inc. (@WhatsApp) Â· Twitter', 'https://twitter.com/WhatsApp', 'whatsapp,whapp,whap,whats,whatsup,social networking, mobile ios android app, whatsapp , fb, whatsapp web , whatsaap twitter computer pc , web, windows, desktop', 'WhatsApp will no longer be supported on Windows Phone after December 31, 2019. You can continue using WhatsApp on Android, iOS or KaiOS devices.', 'images (1).jpg'),
(17, 'WhatsApp Business - Apps on Google Play', 'https://play.google.com/store/apps/details?id=com.whatsapp.w4b&hl=en', 'whatsapp,whapp,whap,whats,whatsup,social networking, mobile ios android app, whatsapp , fb, whatsapp web, business , whatsaap twitter computer pc , web, windows, desktop', ' Rating: 4.4 - â€Ž755,452 votes - â€ŽFree - â€ŽAndroid - â€ŽCommunication\r\nWhatsApp Business enables you to have a business presence on WhatsApp, communicate more efficiently with your customers, and help you grow your ...', 'images.jpg'),
(18, 'WhatsApp Messenger - Apps on Google Play', 'https://play.google.com/store/apps/details?id=com.whatsapp&hl=en', 'whatsapp,whapp,whap,whats,whatsup,social networking, messenger ,mobile ios android app, whatsapp , fb, whatsapp web, business , whatsaap twitter computer pc , web, windows, desktop', 'Rating: 4.4 - â€Ž91,722,618 votes - â€ŽFree - â€ŽAndroid - â€ŽCommunication\r\nWhatsApp Messenger is a FREE messaging app available for Android and other smartphones. WhatsApp uses your phone\'s Internet connection ...', 'images.png'),
(19, 'Instagram', 'https://www.instagram.com/', 'Instagram,Mark zuckerberg giant, insta, inst, insta, insta filters, instagram, social networking, photo and video sharing', 'Create an account or log in to Instagram - A simple, fun & creative way to capture, edit & share photos, videos & messages with friends & family.\r\nInstagram is a photo and video-sharing social networking service owned by Facebook, Inc. It was created by Kevin Systrom and Mike Krieger, and launched in October 2010 exclusively on iOS. ', 'google.com embedded (4).jpeg'),
(20, 'Instagram (@instagram) Â· Twitter', 'https://twitter.com/instagram', 'Instagram,Mark zuckerberg giant, insta, inst, insta, insta filters, instagram, social networking, photo and video sharing, twitter insta,', 'Instagram is a photo and video-sharing social networking service owned by Facebook, Inc. It was created by Kevin Systrom and Mike Krieger, and launched in October 2010 exclusively on iOS. Wikipedia\r\nDate launched: October 6, 2010\r\nAndroid: 98.0.0.15.119 / June 17, 2019; 5 days ago\r\nOwner: Facebook, Inc.\r\nDeveloped by: Facebook, Kevin Systrom, Mike Krieger\r\nAwards: Shorty Award for Apps\r\nNominations: Teen Choice Award for Choice Social Network', 'dreamstime_m_109372725.jpg'),
(21, 'Instagram - Apps on Google Play', 'https://play.google.com/store/apps/details?id=com.instagram.android&hl=en', 'Instagram,Mark zuckerberg giant, insta, inst, insta, insta filters, instagram, social networking,  google play store , app , android app , iosphoto and video sharing, twitter insta,', ' Rating: 4.5 - â€Ž83,882,001 votes - â€ŽFree - â€ŽAndroid - â€ŽSocial Networking\r\nInstagram is a simple way to capture and share the world\'s moments. Follow your friends and family to see what they\'re up to, and discover accounts from all ...\r\n', 'google.com embedded (5).jpeg'),
(22, 'Instagram on the App Store - Apple', 'https://apps.apple.com/us/app/instagram/id389801252', 'Instagram,Mark zuckerberg giant, insta, inst, insta, insta filters, instagram, ios appstore social networking,  google play store , app , android app , iosphoto and video sharing, twitter insta,', ' Rating: 4.8 - â€Ž11,905,077 reviews - â€ŽFree - â€ŽiOS - â€ŽEntertainment\r\nThis app is only available on the App Store for iOS devices. ... Instagram is a simple way to capture and share the worldâ€™s moments. ... Compatible with iPhone, iPad, and iPod touch.', 'images (2).jpg'),
(23, 'Instagram - Home | Facebook', 'https://www.facebook.com/instagram/', 'Instagram,Mark zuckerberg giant, fb insta  insta, inst, insta, insta filters, instagram, ios appstore social networking,  google play store , app , android app , iosphoto and video sharing, twitter in', 'https://www.facebook.com â€º Pages â€º Other â€º Brand â€º App Page\r\n Rating: 3.9 - â€Ž27,917 votes\r\nInstagram. 60148885 likes Â· 26927 talking about this. Bringing you closer to the people and things you love. â¤ï¸\r\nInstagram - Wikipedia', 'images (3).jpg'),
(24, 'Google', 'https://www.google.com/', 'google, google search engine, Google, goog, gogle. google, search engine ,  our competitor biggest, worlds best search engine,search engine top, big tech giant, sundar pichai , larry page', 'Even more from Google Â· Sign in. Google. Ã—. Ã—. SEND FEEDBACK. CANCEL. OK. DELETE. Location unavailable - -. SettingsSearch settingsAdvanced ...\r\nGoogle LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, search engine, cloud computing, software, and hardware. It is considered one of the Big Four technology companies, alongside Amazon, Apple and Facebook. Wikipedia\r\nCEO: Sundar Pichai (Oct 2, 2015â€“) Trending\r\nFounded: September 4, 1998, Menlo Park, California, United States\r\nParent organization: Alphabet Inc. (2015â€“)\r\nSubsidiaries: YouTube, Google.org, Dialogflow, Google Nest, MORE\r\nFounders: Larry Page, Sergey Brin\r\nDid you know: Google is the world\'s largest internet company by revenue. wikipedia.org', 'google.com embedded (1).png'),
(25, 'Google (@Google) Â· Twitter', 'https://twitter.com/Google', 'google, Google, goog, gogle, twitter google, google, search engine ,  our competitor biggest, worlds best search engine,search engine top, big tech giant, sundar pichai , larry page', 'CEO: Sundar Pichai (Oct 2, 2015â€“) Trending\r\nFounded: September 4, 1998, Menlo Park, California, United States\r\nParent organization: Alphabet Inc. (2015â€“)\r\nSubsidiaries: YouTube, Google.org, Dialogflow, Google Nest, MORE\r\nFounders: Larry Page, Sergey Brin\r\nDid you know: Google is the world\'s largest internet company by revenue.', 'google.com embedded.png'),
(26, 'Google - Information Technology Company - Mountain View ...', 'https://www.facebook.com/Google/', 'google, Google, goog, gogle,  fb google ,twitter google, google, search engine ,  our competitor biggest, worlds best search engine,search engine top, big tech giant, sundar pichai , larry page', 'Google, Mountain View, CA. 27M likes. Organizing the world\'s information and making it universally accessible and useful.\r\n', 'google.com embedded (2).png'),
(27, 'Google Safety Center', 'https://safety.google/', 'google, Google, goog, gogle, safety centre google,  fb google ,twitter google, google, search engine ,  our competitor biggest, worlds best search engine,search engine top, big tech giant, sundar pich', 'From day one at Google, we established a principle that has influenced everything we\'ve made since, and everything we\'ll make moving forward â€“ respect the ...', 'google.com embedded (7).jpeg'),
(28, 'Google Account', 'https://www.google.com/', 'google, Google, goog, gogle, mail, account,  fb google ,twitter google, google, search engine ,  our competitor biggest, worlds best search engine,search engine top, big tech giant, sundar pichai , la', 'Personal info - Data & personalization - Security - ...\r\nAccess Google Calendar with a free Google account (for ...\r\nGmail is email that\'s intuitive, efficient, and useful. 15 GB of ...\r\nFind a place. Your location. Trails. Dedicated lanes. Bicycle ...', 'Logo_Google_2013_Official.svg.png'),
(29, 'Geo News', 'https://www.geo.tv/', 'Geo , geo , news , geo news , urdu news, hamid mir, geo news , tv , geo news tv , pakistani news channel,', 'Geo News is a Pakistani pay television news channel owned by the Independent Media Corporation, a company owner of the Jang Group of Newspapers.\r\nGeo TV provides latest news, breaking news, urdu news from pakistan, world, sports, cricket, business, politics, health. watch geo news on live.geo.tv.', 'google.com.pk embedded (1).png'),
(30, 'BBC World News', 'https://www.bbc.com/news', 'bbc, news , bbc urdu , bbc world. bbc world news, news', 'BBC News provides trusted World and UK news as well as local and ... The latest global news, sport, weather and documentaries ... BBC World Service Radio.\r\nBBC News is an operational business division of the British Broadcasting Corporation responsible for the gathering and broadcasting of news and current affairs. Wikipedia\r\nOwner: BBC\r\nHeadquarters: London, United Kingdom\r\nFounded: November 14, 1922, Central London, London, United Kingdom\r\nNumber of employees: 3,500 (2,000 are journalists)', 'google.com embedded (3).png'),
(31, 'YouTube', 'https://www.youtube.com/', 'Youtube, you, yout, tube, youtube, youtube, google youtube , youtube , Susan Wojcicki, T-series, Pewdiepie', 'Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube.\r\nYouTube is an American video-sharing website headquartered in San Bruno, California. Three former PayPal employeesâ€”Chad Hurley, Steve Chen, and Jawed Karimâ€”created the service in February 2005. Google bought the site in November 2006 for US$1.65 billion; YouTube now operates as one of Google\'s subsidiaries. Wikipedia\r\nHeadquarters: San Bruno, California, United States Trending\r\nFounded: February 14, 2005, San Mateo, California, United States\r\nCEO: Susan Wojcicki (Feb 5, 2014â€“)\r\nAcquisition date: November 13, 2006\r\nFounders: Jawed Karim, Steve Chen, Chad Hurley\r\nParent organization: Google', 'google.com embedded (4).png'),
(32, 'YouTube - Apps on Google Play', 'https://play.google.com/store/apps/details?id=com.google.android.youtube&hl=en', 'Youtube, you, yout, tube, youtube, youtube, app youtube, android , app, google youtube , youtube , Susan Wojcicki, T-series, Pewdiepie', ' Rating: 4.4 - â€Ž48,200,870 votes - â€ŽFree - â€ŽAndroid - â€ŽEntertainment\r\nGet the official YouTube app for Android phones and tablets. See what the world is watching -- from the hottest music videos to what\'s trending in gaming, ...\r\n', 'google.com embedded (5).png'),
(33, 'YouTube (@YouTube) Â· Twitter', 'https://twitter.com/YouTube', 'Youtube, you, yout, tube, youtube, twitter, youtube, app youtube, android , app, google youtube , youtube , Susan Wojcicki, T-series, Pewdiepie', 'YouTube Videos\r\nShare your videos with friends, family, and the world.\r\nMusic\r\nYouTube\'s music destination featuring top tracks and popular ...\r\nPopular on YouTube\r\nThe pulse of what\'s popular on YouTube. Check out the latest ...\r\nYouTube Music\r\nSubscribe to the YouTube Music channel to stay up on the latest ...', 'google.com embedded (6).png'),
(34, 'YouTube - Wikipedia', 'https://en.wikipedia.org/wiki/YouTube', 'Youtube, you, yout, tube,  wiki,youtube, twitter, youtube, app youtube, android , app, google youtube , youtube , Susan Wojcicki, T-series, Pewdiepie', 'YouTube is an American video-sharing website headquartered in San Bruno, California. Three former PayPal employeesâ€”Chad Hurley, Steve Chen, and ...\r\nProductsâ€Ž: â€ŽYouTube Musicâ€Ž; â€ŽYouTube TV	Industryâ€Ž: â€ŽInternet; â€ŽVideo hosting service\r\nKey peopleâ€Ž: â€ŽSusan Wojcickiâ€Ž (â€ŽCEOâ€Ž)	Advertisingâ€Ž: â€ŽGoogle AdSense', 'images (1).png'),
(35, 'Official YouTube Blog', 'https://youtube.googleblog.com/', 'Youtube, you, yout, tube, article , blog. wiki,youtube, twitter, youtube, app youtube, android , app, google youtube , youtube , Susan Wojcicki, T-series, Pewdiepie', 'YouTube Music and Universal Music Group change the way you see music. Wednesday, June 19, 2019. Great music videos are works of art that continue to ...', 'google.com embedded (7).png'),
(36, 'RAJA AHMED |   Ø±Ø§Ø¬Û Ø§Ø­Ù…Ø¯', 'https://www.facebook.com/raja.ahmed.52012', 'raja, ahmed, sajjad, raja ahmed sajjad, Ø±Ø§Ø¬Û Ø§Ø­Ù…Ø¯,ceo reliance, C.E.O , hss takhar,reliance, Reliance , Reliance Search Engine, Our Ceo, ceo and developer of this engine search,', 'C.E.O RELIANCE INC. \r\nIT & TECH, ENTREPRENEURSHIP, WRITING,DISCOVERIES & INNOVATIONS, SINGING,EXPLORING BIOGRAPHIES\r\nFreelancer at Fiverr\r\nStudies Computer Systems Engineering at UET Peshawar\r\nStudied Pre-Engineering at The peace Group of Colleges\r\nStudied Science at Pine Hills Public School & College Abbottabad Pakistan\r\nWent to Pine Hills Public School And College Abbottabad\r\nLives in Peshawar, Pakistan\r\nFrom Abbottabad\r\nSingle', 'SPEX5277.jpg'),
(37, 'Ashley Alex Jacob', 'https://www.facebook.com/ashleyjacob.pk', 'Ashley, Alex Jacob, Ashley Alex JAcob, Ashley, aashley, dost, graphic designer', 'Enthusiast for a Better Pakistan | Human Being| Engineering Student | Graphics Designer |\r\nStudies at UET Peshawar\r\nWent to Edwardes College Peshawar\r\nWent to st.marys high school\r\nLives in Peshawar, Pakistan\r\nFrom Peshawar, Pakistan', '53682544_2082788658486212_7083235497350266880_n.jpg'),
(38, 'Abdul Haadi', 'https://www.facebook.com/abdulhadiayaz', 'haadi, Abdul hadi , haadi , hadi , ayaz, baba', 'Went to PISJ - Pakistan International School, Jeddah\r\nWent to Al Watan International School, Jeddah\r\nFrom Jeddah, Saudi Arabia\r\nFollowed by 1,062 people\r\ni7adii\r\nabhadii.sarahah.com', '48386023_1427270454076311_6364120266758422528_n.jpg'),
(39, 'Daniyal Khan', 'https://www.facebook.com/profile.php?id=100007423025695&fref=pb&hc_location=friends_tab', 'Daniyal khan , dani , daani , daniyal ,edwardian', 'tudies at UET Peshawar\r\nStudied at Edwardes College\r\nWent to Edwardes college school\r\nLives in Peshawar, Pakistan\r\nFrom Peshawar, Pakistan', '58383745_2321268771463868_8047284045588987904_n.jpg'),
(40, 'Humam Ahmad Khan', 'https://www.facebook.com/albert.ahmad.9', 'Humam , crocs\r\n, ahmad, humam ahmad khan, humam ahmed khan', 'excuse me but boo.\r\nLives in Karachi, Pakistan\r\nFrom Mardan\r\nHe\'s good at jokes , karachi ka bhaiyaa , altaf bhai ka fan \r\nLikes to wear crocks !!!', '52768868_1117984501715300_1199018164529135616_n.jpg'),
(41, 'Ali Asghar', 'https://www.facebook.com/profile.php?id=100009950341792', 'Ali, asghar, ali asghar, batsman, miraasi', 'Studies at University of Engineering & Technology Peshawar\r\nJoined June 2015\r\nGood at batting and dancing ,\r\nft at Mein miraasi mera ........', '58382803_856215814720089_9210046995308216320_n.jpg'),
(42, 'Syed Zeeshan Hussain ', 'https://www.facebook.com/profile.php?id=100006371196425', 'zeeshi, zeeshan, syed saab, syed, swabi, saudia, hussain,', 'Worked at Work as a student\r\nStudied at The Quaid-e-Azam Group of schools and Colleges KPK\r\nStudies at UET Peshawar\r\nStudies Computer systems engineering at University of Engineering and Technology Peshawar Pakistan\r\nWent to Quaid e Azam Public School, Swabi\r\nLives in Peshawar, Pakistan\r\nAims At Ethical hacking and jugaar\r\nGoing to KSA soon', '56702369_2264984940390524_143654544243425280_n.jpg'),
(43, 'Abul Kalam Ghauri', 'https://www.facebook.com/profile.php?id=100011691445845', 'kalam, abul, kalam , cr , mardan , islamian', 'studying at Islamia college Peshawer\r\nStudies at UET Peshawar\r\nStudied at Islamia College Peshawar [Official]\r\nWent to Aziz Bhatti Shaheed Army Public school & College Mardan', '49708593_754042161662158_5207994012174123008_n.jpg'),
(44, ' Abdul Aziz Khan', 'https://www.facebook.com/aziz.khan.75436531', 'Aziz Khan, aziz, gaju khan , baba gaju, aziz , swabi, air uni', 'Proud Pakhtoon, Optimistic, Wanderlust...\r\nStudies Computer systems engineering at UET Peshawar\r\nStudied Mechanical engineering at Air University-Islamabad\r\nStudied F.Sc pre engineering at University College for Boys\r\nWent to Forward Model School, Hayatabad\r\nLives in Peshawar, Pakistan\r\nFrom Sawabi, Khyber Pakhtunkhwa, Pakistan\r\nSingle\r\nJoined September 2011', '53808783_1925082474268051_1778787746752495616_n.jpg'),
(45, 'Abdul Mohiz Khalid', 'https://www.facebook.com/abdul.mohiz.1048', 'moiz, mohiz, Abdul Mohiz Khalid, Ceo, apcoft,', 'Studied at Tameer i watan colleges abbotabad\r\nStudies at UET Peshawar\r\nWent to Orash Public School\r\nLives in Abbottabad\r\nFrom Abbottabad\r\nC.E.O APCOFT\r\ngood at bowling and PUBG, programming', '48356293_214086966177664_2458900667092172800_n.jpg'),
(46, 'Hasham Ali Khan', 'https://www.facebook.com/hakbosm', 'hasham , khan, hasham ali, kabaari', 'Come from Kalasin ( Thailand)\r\nStudies at UET Peshawar\r\nStudied at Aziz Bhatti Shaheed Army College, Mardan\r\nStudied at Sudhum Children Academy & Science College\r\nLives in Mardan\r\nFrom Mardan\r\nOwns An Online Crap selling company\r\nAlso known as Kabaari', '58378514_668988076889526_8461728705817870336_n.jpg'),
(47, 'Hunain Khan | Afzal Haq', 'https://www.facebook.com/afza.al.583', 'hunu, afzal , haq, hunain, gaming world, mitha', 'Studied at UET Peshawar\r\nStudied Pre-Engineering at Govt. Degree College Mingora SwatOfficial\r\nWent to Swat Children Academy and College Rungmuhallah Mingora Swat\r\nLives in Peshawar, Pakistan\r\nFrom Swat, Pakistan\r\nSingle\r\nOwns Hunu gaming World\r\nMitha in Hindko', '52392582_402133577028736_6568473827154591744_n.jpg'),
(48, 'Sameer Nawaz Swati', 'https://www.facebook.com/sameer.nawaz.144', 'sameer, sameer nawaz swati , swati', '1 at Body Talk\r\nStudied Computer science at Bright Vision Model College Haripur\r\nStudies Computer Sytems Engineering at UET Peshawar\r\nWent to Pakistan International Public School & College\r\nLives in Peshawar, Pakistan\r\nFrom Haripur, Pakistan\r\nSwaati Saab', '48183822_2208271892772782_6548928109595328512_n.jpg'),
(49, 'Abdul Rehman AR', 'https://www.facebook.com/abdulrehman.arehman.71619', 'AR , rehman, abdul rehman', 'Programmer ðŸŽ§ðŸ’»ðŸ“˜\r\nwhy so much difficult,every wall has door get ready to make deepest penetration :\')\r\nFormer Microsoft Certified at Microsoft Office Specialist\r\nStudies at UET Peshawar\r\nStudied at Peshawar Model Degree Colleges (BOys & GiRLs).\r\nWent to St Mary\'s High School Peshawar, Pk\r\nLives in Peshawar, Pakistan\r\nFrom Peshawar, Pakistan\r\nBiker', '59956086_239153983709203_4709876822014164992_n.jpg'),
(50, 'Sayed Qaisar Ali', 'https://www.facebook.com/sayed.qaisarali', 'qaiser, qaiser ali, ali, syed qaiser , tom cruze, paro', 'Studies Computer Systems Engineering at UET Peshawar\r\nLives in Peshawar, Pakistan\r\nFrom Swat, Pakistan\r\nSingle\r\nKalam\'s paro', '62234321_2207196579395258_6925434267136688128_n.jpg'),
(51, 'Rasool Zahid', 'https://www.facebook.com/profile.php?id=100010874647898', 'rasool zada, zada, zahid, rasool', '\"Silence is golden when you can\'t think of a good answer\"\r\nStudies at UET Peshawar\r\nStudied at UET Peshawar\r\nWent to Youth Hostel Bannu\r\nWent to Sarwarjan pilot high school,Bamna,Barguna\r\nLives in Bannu\r\nFrom Bannu Cantonment, Khyber Pakhtunkhwa, Pakistan', '55576678_788769618162186_982325734322208768_n.jpg'),
(52, 'Syed Umair Shah Bukhari', 'https://www.facebook.com/usempire.us', 'usb, umair , shah , bukhari , umair', 'Nothing Except To Believe In US Empire\r\nStudent at NoT YeT WorkinG I\'m Still StudinG\r\nStudies at UET Peshawar\r\nStudied Top Student of the graduating class at University Wensam College D.I.Khan\r\nWent to university WENSAM college\r\nWent to University Wensam College D.I.Khan\r\nFrom Gomal, Khyber Pakhtunkhwa, Pakistan\r\nIn a relationship\r\nUSB', '60095342_2354184018200281_4566864160633126912_n.jpg'),
(53, 'Muhammad Ullah', 'https://www.facebook.com/profile.php?id=100006854176091', 'muhammadullah, muhammad, ', '#PROGRAMMER\r\nPeshawar at UET Peshawar\r\nStudies at UET Peshawar\r\nStudied at HIST Hangu\r\nWent to The Wisdom Institute of Science & Technology Hangu', '42503658_2124840174421101_7181712508967714816_n.jpg'),
(54, 'Jamshid Ali ', 'https://www.facebook.com/jamshidalionesix54', 'jamshid bhai, jamshaid, jamshed,j', ' Self Employed at Shaadi Mubarak \r\n\"Intelligence plus character -that is the goal of true education\"\r\nStudies Computer Systems Engineering at UET Peshawar\r\nStudied Pre-Engeneering at Govt PG Jahanzeb College Saidu Sharif Swat\r\nWent to Ghazali Public High School Asbanr, Dir - Lower\r\nLives in Peshawar, Pakistan\r\nFrom Chakdara Fort, Khyber Pakhtunkhwa, Pakistan\r\nSingle Good at Project designing\r\n\r\n', '45479899_744757679191189_2411687148169199616_n.jpg'),
(55, 'Mubashir Saeed', 'https://www.facebook.com/mubashir.saeed.5015', 'mubashir , saeed , chotu', 'ft AT CHOTU \r\nm Ã¤ $Ã¯mpÂ£Ã« pÃ«r$0Ã± ÅµÃ¯th Ã§0mpÂ£Ã¯Ã§Ã¤tÃ«d mÃ¯Ã±d, thÃ£t Ã¿0Ã» Ã§Ã¢Ã±\'t Ã»Ã±dÃªrÂ§tÃ£Ã±d............\r\nStudies Computer System Engineering at UET Peshawar\r\nStudied F. Sc. Pre Engineering at F.G Degree College For Men Wah Cantt\r\nWent to F.G Boys High School No.7 Wah Cantt\r\nLives in Wah, Pakistan\r\nFrom Khanpur, Khyber Pakhtunkhwa, Pakistan\r\nSingle\r\n\r\n', '26231334_2045538739026469_4184527004424345081_n.jpg'),
(56, 'Mega Buzz Event UET PESHAWAR', 'https://www.uetpeshawar.edu.pk/', 'Mega Buzz , mega , buzz , event , uet peshawar', 'Full fledge Event held at UET Peshawar .\r\nUnder the Flagship of CS Computer Scoiety', 'detaled .jpg'),
(57, 'APCOFT .INC', 'www.apcoft.inc', 'apcoft, ap, mohiz, ceo apcoft', 'APCOFT A TECH GIANT !!!', '48356293_214086966177664_2458900667092172800_n.jpg'),
(58, 'DCSE Computer Systems Engineering Department UET PESHAWAR', 'www.dcse.uetpeshawar.edu.pk.com', 'dcse, batch 20, uet ,computer systems department, cse', 'DCSE Computer Systems Engineering Department UET PESHAWAR\r\ndcse, batch 20, uet ,computer systems department, csedcse, batch 20, uet ,computer systems department, csedcse, batch 20, uet ,computer systems department, csedcse, batch 20, uet ,computer systems department, csedcse, batch 20, uet ,computer systems department, cse', '42604127_2755586161124627_2140681072638164992_n.jpg'),
(59, 'UET PESHAWAR', 'www.uetpeshawar.edu.pk', 'UET , uet , pesh,peshawar,pekhawar, university of engineering and technology', 'university of engineering and technologyUET , uet , pesh,peshawar,pekhawar, university of engineering and technologyUET , uet , pesh,peshawar,pekhawar, university of engineering and technologyUET , uet , pesh,peshawar,pekhawar, university of engineering and technology\r\nUET PESHAWAR\r\nwww.uetpeshawar.edu.pk', '210px-University_of_Engineering_and_Technology_Peshawar_logo.svg.png'),
(60, 'dcse library', 'dcse.lib.in', 'dcse , library, books, cse ', 'Library and a place to thrive and shine situated at DCSE.', '44227021_2451655591543704_2013695159031562240_n.jpg'),
(61, 'Engr. Madiha Sher | Lecturer at UET PESHAWAR', 'www.scholar.google.com', 'madiha, sher , madam , madiha , ma\'m, mam, cp ', 'Engr. Madiha Sher | Lecturer at UET PESHAWAR\r\nmadiha, sher , madam , madiha , ma\'m, mam, cp madiha, sher , madam , madiha , ma\'m, mam, cp ', '31820685_2139822869393646_6190977885809934336_n.jpg'),
(62, 'Passwords.com', 'D:\\MY PC\\E\\CREDIENTIALS\\PASSWORDS.txt', 'Password,pass,passcode,word', 'This is my database of sensitive passcodes', '905.jpg'),
(63, 'Abdullah\'s Store', 'www.arstiae.weebly.com', 'abdullah,shan,ahmed,hassan, store, abd , store, Stire', 'hsdygfiyuwekgjsdkfg\r\ndfjgbkjdfkjgksdfg\r\nsdfghkjsdfhgkjdsfkg\r\nsdfjgbdifgj', 'google.com embedded (3).png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `website`
--
ALTER TABLE `website`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `website`
--
ALTER TABLE `website`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=64;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
